### ISSUE TITLE
Unable to start the bot due to error

### ISSUE THREAD

**Issue by tanookiben** [CharlieHess/slack-poker-bot#2]
Here's the output of running `node src/main.js` after `npm install`

```
➜  slack-poker git:(master) ✗ node src/main.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ben/apps/slack-poker/node_modules/babel/register.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by tanookiben** [comment]
Got past the issue above (fresh `npm install`), but now I'm running into a new error:

```
➜  slack-poker git:(master) ✗ node src/main.js
[Mon Jul 06 2015 00:58:12 GMT-0400 (EDT)] INFO Connecting...
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Client.emit (events.js:87:13)
    at Client._onLogin (/home/ben/apps/slack-poker/node_modules/slack-client/src/client.js:74:14)
    at /home/ben/apps/slack-poker/node_modules/slack-client/src/client.js:2:59
    at IncomingMessage.<anonymous> (/home/ben/apps/slack-poker/node_modules/slack-client/src/client.js:670:22)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by tanookiben** [comment]
My mistake, I'm stupid T_____T the bot happened to be disabled in the Slack admin panels

**Comment by quentinlebras** [comment]
@tanookiben hello our poker bot seems "away" in the user list

![capture d ecran 2015-09-04 14 18 35](https://cloud.githubusercontent.com/assets/6772424/9683377/dc86ff12-530f-11e5-8901-3ad983d323a3.png)

how did you enabled it?

**Comment by CWSpear** [comment]
I'm getting this error, too, but my bot _is_ enabled.

**Comment by CWSpear** [comment]
Argh... my issue was because I had a typo in my token. Copy and paste fail =/

@quentinlebras if you're seeing this error, first of all... make sure your token is correct! 

If it is a matter of being disabled, to enable it: go to the admin page for services (https://limitbreak.slack.com/services), click on Bots and then click on your bot and there should be an enable/disable button in the top right corner.

If the bot isn't connected to something (i.e. if the server isn't running), it will appear as away. Once the server is successfully working, it'll show up as **active**.
